<div class="bodyIndex">
  <div class="bannerTeste">
    <nav class="navegador">
      <ul class="ul">
        <li class="li"><a class="a" href="/">Inicial</a></li>
        <li class="li"><a class="a" href="/novo">Cadastre-se</a></li>
        <li class="li"><a class="a" href="/login">Login</a></li>
        <li class="li"><a class="a" href="/sobre">Sobre nós</a></li>
      </ul>
    </nav>      
  </div>
    <header>
      
    </header>

    
      <div class="corpo">
        <span class=""><h3>Produtos recentes</h3>
        <h6>Verifique nossos produtos mais recentes abaixo!</h6></span>
        
            <?php 
            $C=2;
              foreach($this->view->produtosHE as $codProd=>$produtoHE){
                if($C==2){
                ?>
                
              
                <?php for ($i=0; $i <= 0; $i++) { 
                  foreach($this->view->produtosHE as $codProd=>$produtoHE){
                
                
                 ?>
                  <div class="infoBox">
                  <img src="/img/camisateste.jpg">
                  <p><?=$produtoHE['descProd']?> - <?=$produtoHE['tamProd']?></p>
                  <span><?=$produtoHE["vlrUnitVen"]?></span>
                </div> <?php }} ?>
                
              </div>
             
                          
            <?php $C=1; }}?>
       
       <div class="base">
         <?php for($i=1;$i<= $this->view->totalPaginasHE; $i++){ ?>
                <li class="circul"><a class="circul" href="?produtosRecentes=<?=$i?>"><?=$i?></a></li>
                 <?php }?>
        </div>

      </div>
    <footer>
      <p>&copy;2022 - Yan Fonseca.</p>
    </footer>
</div>
