<div class="bodyIndex">
  <div class="bannerTeste">
    <nav class="navegador">
      <ul class="ul">
        <li class="li"><a class="a" href="/">Inicial</a></li>
        <li class="li"><a class="a" href="/novo">Cadastre-se</a></li>
        <li class="li"><a class="a" href="/login">Login</a></li>
        <li class="li"><a class="a" href="/sobre">Sobre nós</a></li>
      </ul>
    </nav>      
  </div>
      
      <div class="corpo">
        <span><h3>Produtos recentes</h3>
        <h6>Verifique nossos produtos mais recentes abaixo!</h6></span>
        <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
          <div class="carousel-inner">
            <?php 
            $C=2;
              foreach($this->view->produtosHE as $codProd=>$produtoHE){
                if($C==2){
                ?>
                
              <div class="carousel-item active">
                <?php for ($i=0; $i <= 0; $i++) { 
                  foreach($this->view->produtosHE as $codProd=>$produtoHE){
                
                
                 ?>
                  <div class="infoBox">
                  <img src="/img/camisateste.jpg">
                  <p><?=$produtoHE['descProd']?> - <?=$produtoHE['tamProd']?></p>
                  <span><?=$produtoHE["vlrUnitVen"]?></span>
                </div> <?php }} ?>
                
              </div>
             
                          
            <?php $C=1; }else{ ?>
              <div class="carousel-item">
                 <?php for ($i=0; $i <= 0; $i++) { 
                  foreach($this->view->produtosHE as $codProd=>$produtoHE){
                
                
                 ?>
                  <div class="infoBox">
                  <img src="/img/sapatoteste.jpg">
                  <p><?=$produtoHE['descProd']?> - <?=$produtoHE['tamProd']?></p>
                  <span><?=$produtoHE["vlrUnitVen"]?></span>
                </div> <?php }} ?>
              </div>

            <?php }}?>
       </div>


    
  
  <button class="ctrlBtnAn" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev" >
    <i class="fa-solid fa-chevron-left fa-2x"></i>
  </button>
  <button class="ctrlBtnPr" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
   <i class="fa-solid fa-chevron-right fa-2x"></i>
  </button>
</div>
      </div>
    <footer>
      <p>&copy;2022 - Yan Fonseca.</p>
    </footer>
</div>
