 
  <body class="body text-center">
    <form class="form-signin" method="POST" action="/autenticar">
      <a href= "/"><img style="border-radius:10px;" class="mb-4" src="/img/logo.png" alt="" width="72" height="72"></a>
      <h1 class="h3 mb-3 font-weight-normal">Conecte-se por favor</h1>
      <input type="text" id="inputEmail" class="form-control" placeholder="endereço de Email" required="" autofocus="" name="email">
      <input type="password" id="inputPassword" class="form-control" placeholder="senha" required="" name="senha">
     
        <?php if($this->view->login== 'erro'){ ?>
				
					<div class='row'>
						<div class="col">
							<span class="text text-danger">*Email ou senha inválidos</span>
						</div>
					</div> <?php } ?>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
       <a style="margin-top: 20px; margin-bottom: 20px; font-size: 18px;" href="/novo">Novo por aqui?! Crie uma conta!</a>
      <p class="mt-5 mb-3 text-muted">Yan Fonseca © 2016-2020</p>
    </form>