    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body>
   <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Projeto genérico</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Pesquisa" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3 active" href="/info"><i class="fa-solid fa-id-badge"></i> <?= $_SESSION['nome']?></a>
    </div>
  </div>
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="/sair"><i class="fa-solid fa-door-open"></i> <i class="fa-solid fa-person-running"></i> Sair</a>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="/inicial">
              <span data-feather="home"></span>
              Informação Geral <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/pedidos">
              <span data-feather="pedidos"></span>
              Pedidos
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/produtosAtivos">
              <span data-feather="produtos"></span>
              Produtos
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/historicoEstoque">
              <span data-feather="estoque"></span>
              Estoque
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Pessoal
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>
       <?php if($_SESSION['rank']<9){ 
            error_reporting(0);?>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="tab-content" id="nav-tabContent">
        <div class='tab-pane fade show active' id="nav-estoque" role="tabpanel" aria-labelledby="nav-home-tab">
          <nav class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"><h1 class="h2">Cofigurações & Informações</h1> 
          </nav>

          <div class="row">
          <div class="col-md-4">
              <br>
          </div>
          <div class="col-md-4 card">
            <h4 class="pt-3 pb-2 mb-3 border-bottom">Refatoração de senha</h4>
            <form class="form-inline card-body" action="/alterarSenha" method="post">

                <div class="input-group mb-2">
                   <span class="input-group-text">Senha atual</span>
                <input type="text" class="form-control" value="<?= $_SESSION['id'];?>" name="idUsuario" hidden="hidden">
                <input type="password" class="form-control" value="<?php if($this->view->erroNewPass=='erro'){echo $this->view->usuario['oldpass'];} else{}?>" id="inputPassword2" required="" name="oldpass" placeholder="Insira senha atual">
              </div>
               <div class="input-group mb-2">
                   <span class="input-group-text">Nova senha</span>
                <input type="password" class="form-control" value="<?php if($this->view->erroNewPass=='erro'){echo $this->view->usuario['newpass'];} else{}?>" id="inputPassword2" required="" placeholder="Insira nova senha" name="newpass">
              </div>
                <div class="d-grid gap-2  mb-2">
                 <button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Alterar senha</button>
               </div>
               <?php if($this->view->erroNewPass== 'erro'){ ?>
            
              <div class='row'>
                <div class="col">
                  <span class="text text-danger">*Senha anterior inválida, ou, nova senha muito curta!</span>
                </div>
              </div> <?php } ?>
            </form>  
          <?php }else{ ?> 

                
            <form class="form-inline" action="/alterarSenha" method="post">
                <div class="form-group mx-sm-3 mb-2">
                   <input type="text" class="form-control" value="<?= $_SESSION['id'];?>" name="idUsuario" hidden="hidden">
               <div class="input-group mx-sm-3 mb-2">
                   <span class="input-group-text">Senha atual</span>
                <input type="password" class="form-control" value="<?php if($this->view->erroNewPass=='erro'){echo $this->view->usuario['oldpass'];} else{}?>" id="inputPassword2" required="" name="oldpass" placeholder="Insira sua senha atual">
              </div>
               <div class="input-group mx-sm-3 mb-2">
                   <span class="input-group-text">Nova senha</span>
                <input type="password" class="form-control" value="<?php if($this->view->erroNewPass=='erro'){echo $this->view->usuario['newpass'];} else{}?>" id="inputPassword2" required="" placeholder="Insira sua nova senha" name="newpass">
              </div>
               <div class="d-grid gap-2 mb-2">
                 <button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Alterar senha</button>
               </div>
               <?php if($this->view->erroNewPass== 'erro'){ ?>
            
              <div class='row'>
                <div class="col">
                  <span class="text text-danger">*Senha anterior inválida, ou, nova senha muito curta!</span>
                </div>
              </div> <?php } ?>
            </form>
          <?php } ?>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-2">
        </div>
                <div class="col-md-8 card">
          <h4 class="pt-3 pb-2 mb-3 border-bottom">Seus dados</h4>
        <form class="form-inline card-body">
        <div class="input-group mb-3">
           <span class="input-group-text">Nome completo</span>
  <input type="text" class="form-control" value="<?= $_SESSION['nome'];?>"  aria-describedby="button-addon2">
  <button class="btn btn-outline-secondary" type="button" id="button-addon2">Editar</button>
</div>

<!-- Pegar dados com PHP -->
<div class="input-group mb-3">
           <span class="input-group-text">Nick</span>
  <input type="text" class="form-control" value="<?= $_SESSION['nome'];?>"  aria-describedby="button-addon2">
  <button class="btn btn-outline-secondary" type="button" id="button-addon2">Editar</button>
</div>
<div class="input-group mb-3">
           <span class="input-group-text">E-mail</span>
  <input type="text" class="form-control" value="<?= $_SESSION['nome'];?>"  aria-describedby="button-addon2">
  <button class="btn btn-outline-secondary" type="button" id="button-addon2">Editar</button>
</div>
<div class="input-group mb-3">
           <span class="input-group-text">Nascimento</span>
  <input type="date" class="form-control" value="<?= $_SESSION['nome'];?>"  aria-describedby="button-addon2">
  <button class="btn btn-outline-secondary" type="button" id="button-addon2">Editar</button>
</div>
<div class="input-group mb-3">
           <span class="input-group-text">Última alteração</span>
  <input type="text" class="form-control" value="<?= $_SESSION['nome'];?>"  aria-describedby="button-addon2">
</div>
</form>
      </div>
      </div>
      <div class="row">
        <div class="col">
          
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>RG</th>
                  <th>CPF</th>
                  <th>Nome</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
              </tbody>
            </table>
          </div>
      </div>
    </div>
  </div>
</main>
