    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      
    </style>   
  </head>
  <body>
    <?php
        $linkAtual= str_replace("","",$_SERVER['REQUEST_URI']);

        $linkteste=(preg_match('?(\d+)$?',$linkAtual,$matches))? $linkteste=$matches[1]: $linkteste='';
        $hisEs='/historicoEstoque?paginaHE=';
        $hisE='/historicoEntrada?paginaE=';
        $hisS='/historicoSaida?paginaS=';
     ?>
  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Projeto genérico</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Pesquisa" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="/info"><?= $_SESSION['nome']?></a>
    </div>
  </div>
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="/sair">Sair</a>
    </div>
  </div>
  </header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="/inicial">
              <span data-feather="home"></span>
              Informação Geral <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/pedidos">
            <!-- Icone -->
              Pedidos
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/produtosAtivos">
              Produtos
            </a>
         
          <li class="nav-item">
            <a class="nav-link Active" href="/historicoEstoque">
              <span data-feather="estoque"></span>
              Estoque
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Pessoal
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>-- SUBMENU Estoque</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a <?= $resultadolink = $linkAtual == '/historicoEstoque'||$linkAtual==$hisEs.$linkteste ? "class='nav-link active'": "class='nav-link'";?> href="/historicoEstoque">
              <span data-feather="file-text"></span>
              Histórico Estoque
            </a>
          </li>
          <li class="nav-item">
            <a <?= $resultadolink = $linkAtual == '/historicoSaida' || $linkAtual==$hisS.$linkteste ? "class='nav-link active'": "class='nav-link'";?> href="/historicoSaida">
              <span data-feather="file-text"></span>
              Histórico Saída
            </a>
          </li>
          <li class="nav-item">
            <a <?= $resultadolink = $linkAtual == '/historicoEntrada'||$linkAtual==$hisE.$linkteste ? "class='nav-link active'": "class='nav-link'";?> href="/historicoEntrada">
              <span data-feather="file-text"></span>
              Histórico Entrada
            </a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Novo Registro</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
         <li class="nav-item">
            <a class="nav-link" data-bs-toggle="modal" data-bs-target="#entrada" type="button">
              <span data-feather="file-text"></span>
              Entrada
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-bs-toggle="modal" data-bs-target="#saida" type="button">
              <span data-feather="file-text"></span>
              Saída
            </a>
          </li>
        </ul>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Gráficos</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
      </div>
    </nav>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="tab-content" id="nav-tabContent">
        <div <?= $resultadolink = $linkAtual == '/historicoEstoque'|| $linkAtual==$hisEs.$linkteste ? "class='tab-pane fade show active'": "class='tab-pane fade show '";?>  id="nav-estoque" role="tabpanel" aria-labelledby="nav-home-tab">
          <nav class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"><h1 class="h2">Estoque</h1> 
          </nav>
          <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>Código</th>
              <th>Descrição</th>
              <th>Tamanho</th>
              <th>Acervo</th>
              <th>Valor unit. compra</th>
              <th>Valor unit. venda</th>
              <th>Entrada recente</th>
              <th>Ação</th>
            </tr>
          </thead>
          <tbody>
             <?php foreach($this->view->produtosHE as $codProd=>$produtoHE){?>
            <tr>
              <td><?=$produtoHE['codProd']?></td>
              <td><?=$produtoHE['descProd']?></td>
              <td><?=$produtoHE['tamProd']?></td>
              <?=$resultHE= $produtoHE['qtde']>$produtoHE['estMaxProd'] ? '<td><button type="button" class="btn-aviso" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Extrapolou limite predefinido!">'.$produtoHE["qtde"].'</button></td>': '<td>'.$produtoHE["qtde"].'</td>'?>
              <td><?=$produtoHE["vlrUnitCom"]?></td>
              <td><?=$produtoHE["vlrUnitVen"]?></td>
              <td><?=$produtoHE['max(N.dataEnt)']?></td>
              
              <td> 
                 <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#editaProd" data-bs-codProd="<?=$produtoHE['codProd']?>" data-bs-descProd="<?=$produtoHE['descProd']?>" data-bs-tamProd="<?=$produtoHE['tamProd']?>" data-bs-qtde="<?=$produtoHE['qtde']?>" data-bs-vlrUnitCom="<?=$produtoHE['vlrUnitCom']?>" data-bs-vlrUnitVen="<?=$produtoHE['vlrUnitVen']?>" data-bs-dataEnt="<?=$produtoHE['max(N.dataEnt)']?>" data-bs-idUsuarioFkProd="<?=$produto['idUsuarioFkProd']?>"
                        ><small>Editar</small></button>
              </td>
            </tr> <?php }?>
          </tbody>
        </table>
      </div>
            <nav class="col-md-9 ml-sm-auto col-lg-10 px-md-4" aria-label="Page navigation">
              <ul class="pagination justify-content-end">
                 <?php if( $this->view->totalPaginasHE >= 2 ) 
                { echo '<li class="page-item"><a class="page-link" href="?paginaHE=1">Primeira</a></li>';}else {'';} ?>
                <?php for($i=1;$i<= $this->view->totalPaginasHE; $i++){ ?>
                <li class="page-item <?=$this->view->paginaAtivaHE==$i ? 'active':''?>"><a class="page-link " href="?paginaHE=<?=$i?>"><?=$i?></a></li>
                 <?php }?>
                <?php if( $this->view->totalPaginasHE >= 2 ) 
                {echo'<li class="page-item"><a class="page-link" href="?paginaHE='.$this->view->totalPaginasHE.'">Última</a></li>';
                }else{echo'';} ?>
              </ul>
            </nav>
        </div>


       <div class="tab-content" id="nav-tabContent">
        <div <?= $resultadolink = $linkAtual == '/historicoSaida'|| $linkAtual==$hisS.$linkteste ? "class='tab-pane fade show active'": "class='tab-pane fade show '";?>  id="nav-saida" role="tabpanel" aria-labelledby="nav-home-tab">
          <nav class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"><h1 class="h2">Histórico Saída</h1> 
          </nav>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>Código</th>
              <th>Descrição</th>
              <th>Tamanho</th>
              <th>Acervo</th>
              <th>Valor unitário</th>
              <th>Entrada recente</th>
              <th>Ação</th>
            </tr>
          </thead>
          <tbody>
             <?php foreach($this->view->produtosS as $codProd=>$produtosS){?>
            <tr>
              <td><?=$produtosS['codProd']?></td>
              <td><?=$produtosS['descProd']?></td>
              <td><?=$produtosS['tamProd']?></td>
              <td><?=$produtosS['qtde']?></td>
              <td><?=$produtosS['vlrUnit']?></td>
              <td><?=$produtosS['dataSai']?></td>
              <td> 
                <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#exampleModal"><small>Editar</small></button>
                <a href="/deletaProd?delProd=deleta&codProd=<?=$produtosS['codProd']?>"class="btn btn-danger"><small>Deletar</small></a>
              </td>
            </tr> <?php }?>
          </tbody>
        </table>
      </div>
            <nav class="col-md-9 ml-sm-auto col-lg-10 px-md-4" aria-label="Page navigation">
              <ul class="pagination justify-content-end">
                  <?php if( $this->view->totalPaginaS >= 2 ) 
                { echo '<li class="page-item"><a class="page-link" href="?paginaS=1">Primeira</a></li>';}else {'';} ?>
                <?php for($S=1;$S<= $this->view->totalPaginaS; $S++){ ?>
                <li class="page-item <?=$this->view->paginaAtivaS==$S ? 'active':''?>"><a class="page-link " href="?paginaS=<?=$S?>"><?=$S?></a></li>
                 <?php }?>
                <?php if( $this->view->totalPaginaS >= 2 ) 
                {echo'<li class="page-item"><a class="page-link" href="?paginaS='.$this->view->totalPaginaS.'">Última</a></li>';
                }else{echo'';} ?>

                
                
              </ul>
            </nav>
        </div>
      </div>
      <div class="tab-content" id="nav-tabContent">
        <div <?= $resultadolink = $linkAtual == '/historicoEntrada'|| $linkAtual==$hisE.$linkteste ? "class='tab-pane fade show active'": "class='tab-pane fade show '";?>  id="nav-entrada" role="tabpanel" aria-labelledby="nav-home-tab">
          <nav class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"><h1 class="h2">Histórico Entrada</h1> 
          </nav>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>Código</th>
              <th>Descrição</th>
              <th>Tamanho</th>
              <th>Data entrada</th>
              <th>Ação</th>
            </tr>
          </thead>
          <tbody>
             <?php foreach($this->view->produtosE as $codProd=>$produtoE){?>
            <tr>
              <td><?=$produtoE['codProdFkEnt']?></td>
              <td><a href="<?=$produtoE['codProdFkEnt']?>" class="link-dado"><?=$produtoE['descProd']?></a></td>
              <td><?=$produtoE['tamProd']?></td>
              <td><?=$produtoE['dataEnt']?></td>
              <td> 
                <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#exampleModal"><small>Editar</small></button>
                <a href="/deletaProd?delProd=deleta&codProd=<?=$produtoE['codProd']?>"class="btn btn-danger"><small>Deletar</small></a>
              </td>
            </tr> <?php }?>
          </tbody>
        </table>
      </div>
       <nav class="col-md-9 ml-sm-auto col-lg-10 px-md-4" aria-label="Page navigation">
              <ul class="pagination justify-content-end">

                <?php if( $this->view->totalPaginasE >= 2 ) 
                { echo '<li class="page-item"><a class="page-link" href="?paginaE=1">Primeira</a></li>';}else {' ';} ?>
                <?php for($E=1;$E<= $this->view->totalPaginasE; $E++){ ?>
                <li class="page-item <?=$this->view->paginaAtivaE==$E ? 'active':''?>"><a class="page-link " href="?paginaE=<?=$E?>"><?=$E?></a></li>
                 <?php }?>
                <?php if( $this->view->totalPaginasE >= 2 ) 
                {echo'<li class="page-item"><a class="page-link" href="?paginaE='.$this->view->totalPaginasE.'">Última</a></li>';
                }else{echo' ';} ?> 
              </ul>
            </nav>
    </div>
  </div>
</div>
    </main>
<!-- Modal -->
<div class="modal fade" id="saida" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <form>
         <input type="text" name="idUsuario" value="<?= $_SESSION['id'];?>" hidden="hidden">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Saída de estoque</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
          <div class="mb-3">
            <select class="form-select" aria-label="Default select example">
            <option selected>Selecione o produto</option> 
            <?php foreach($this->view->produtosT as $codProd=>$produtosT){?>
            <option value="<?=$produtosT['codEst']?>"> <?=$produtosT['descProd']?> - <?=$produtosT['codProdFkEst']?> - <?=$produtosT['tamProd']?></option><?php } ?>
            </select>
          </div>
  <div class="mb-3">
    <input type="number" class="form-control" id="exampleInputEmail1" name="" min="1" placeholder="Quantidade">
  </div>
  <div class="mb-3">
    <input type="number" name="" step="0.01" class="form-control" id="exampleInputPassword1" min= "0.01" placeholder="Valor unitário">
  </div>

      </div>
      <div class="modal-footer">
         <button type="button" class="btn btn-danger">Deletar</button>
        <button type="button" class="btn btn-success">Salvar</button>
      </div>
      </form>
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="entrada" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <form method="POST" action="/postEntEstq">
         <input type="text" name="idUsuario" value="<?= $_SESSION['id'];?>" hidden="hidden">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Entrada de estoque</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
          <div class="mb-3">
           
            <select class="form-select" aria-label="Default select" name="codProd">
            <option selected>Selecione o produto</option> 
            <?php foreach($this->view->produtosC as $codProd=>$produtosC){?>
            <option value="<?=$produtosC['codProd']?>"> <?=$produtosC['descProd']?> - <?=$produtosC['codProd']?> - <?=$produtosC['tamProd']?></option><?php } ?>
            </select>
          
          </div>
  <div class="mb-3">
    <input type="number" class="form-control" name="qtde" min="1" placeholder="Quantidade">
  </div>
  <div class="mb-3">
    <input type="number" name="vlrUnitCom" step="0.01" class="form-control" min= "0.01" placeholder="Valor unit. compra" onchange="this.value = this.value.replace(/,/g, '.')">
  </div>

      </div>
      <div class="modal-footer">
         <button type="button" data-bs-dismiss="modal" aria-label="Close" class="btn btn-danger">Cancelar</button>
        <button  type="submit" class="btn btn-success">Salvar</button>
      </div>
      </form>
    </div>
  </div>
</div>

<div class="modal fade" id="editaProd" tabindex="-1" aria-labelledby="editaProdLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="editaProdLabel"></h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form method="POST" action="/editEstq">
            <div class="modal-body">
              <div class="mb-3 row">
                <div class="col-9">
                  <input type="text" name="codProd" id="codProd"hidden="">
                  <input type="text" name="idUsuario" value="<?= $_SESSION['id'];?>" hidden="hidden">
                  <label for="descProd" class="col-form-label">Descrição:</label>
                  <input type="text" class="form-control" id="descProd" name=""  placeholder="Descrição" readonly="">
                </div>
                <div class="col-3">
                  <label for="tamProd" class="col-form-label">Tamanho:</label>
                  <input type="text" class="form-control" id="tamProd" name="" placeholder="Tamanho" readonly="">
                </div>
              </div>
              <div class="mb-3 row">
                 <div class="col-6">
                  <label for="dataEnt" class="col-form-label">Data entrada</label>
                  <input type="text" readonly="readonly" class="form-control" id="dataEnt" name="" placeholder="Data de entrada">
                </div>
                <div class="col-3">
                  <label for="qtde" class="col-form-label">Quantidade</label>
                  <input type="number" class="form-control" id="qtde" name="qtde" min="1" placeholder="Quantidade" readonly="">
                </div>
                <div class="col-3">
                  <label for="vlrUnitVen" class="col-form-label">Valor unitário</label>
                  <input type="number" class="form-control" id="vlrUnitVen" name="vlrUnitVen" min="1" step="0.01" placeholder="Valor unitário venda">
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close">Cancelar</button>
              <button type="submit" class="btn btn-success">Salvar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
</div>

<script type="text/javascript">
  var editaProd = document.getElementById('editaProd')
    editaProd.addEventListener('show.bs.modal', function (event) {

// Button que altera o estado do modal
    var button = event.relatedTarget

// Enviando valores para variável <--
    var getstatusProd = button.getAttribute('data-bs-dataEnt')
    var getcodProd = button.getAttribute('data-bs-codProd')
    var getdescProd = button.getAttribute('data-bs-descProd')
    var gettamProd = button.getAttribute('data-bs-tamProd')
    var getestMinProd = button.getAttribute('data-bs-qtde')
    var getestMaxProd = button.getAttribute('data-bs-vlrUnitVen')
    var getvlrUnitCom = button.getAttribute('data-bs-vlrUnitCom')
    var getclasseProd = button.getAttribute('data-bs-classeProd')
    var getidUsuarioFkProd = button.getAttribute('data-bs-idUsuarioFkProd')

//Recebendo id do input <--
    var modalTitle = editaProd.querySelector('.modal-title')
    var setstatusProd = editaProd.querySelector('#dataEnt')
    var setcodProd = editaProd.querySelector('#codProd')
    var setdescProd = editaProd.querySelector('#descProd')
    var settamProd = editaProd.querySelector('#tamProd')
    var setestMinProd = editaProd.querySelector('#qtde')
    var setestMaxProd = editaProd.querySelector('#vlrUnitVen')
     var setvlrUnitCom = editaProd.querySelector('#vlrUnitCom')
    var setclasseProd = editaProd.querySelector('#classeProd')
    var setidUsuarioFkProd = editaProd.querySelector('#idUsuarioFkProd')


//Exibindo valores recebidos nas variáveis no input dentro do modal <--
    modalTitle.textContent = 'Editar produto de código [ ' + getcodProd + ' ]'
    setcodProd.value = getcodProd
    setstatusProd.value = getstatusProd
    setdescProd.value = getdescProd
    settamProd.value = gettamProd
    setestMinProd.value = getestMinProd
    setestMaxProd.value = getestMaxProd
    setvlrUnitCom.value = getvlrUnitCom
    setclasseProd.value = getclasseProd
    setidUsuarioFkProd.value = getidUsuarioFkProd
  })
</script>