    <?php
        $linkAtual= str_replace("","",$_SERVER['REQUEST_URI']);
        $linkteste=(preg_match('?(\d+)$?',$linkAtual,$matches))? $linkteste=$matches[1]: $linkteste='';
        $prodA='/produtosAtivos?pagina=';
        $prodI='/produtosInativos?paginaI=';
     ?>
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>   
  </head>
  <body>
   <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Projeto genérico</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Pesquisa" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="/info"><?= $_SESSION['nome']?></a>
    </div>
  </div>
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="/sair">Sair</a>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="/inicial">
              <span data-feather="home"></span>
              Informação Geral <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/pedidos">
            <!-- Icone -->
              Pedidos
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="/produtosAtivos">
              Produtos
            </a>
         
          <li class="nav-item">
            <a class="nav-link" href="/historicoEstoque">
              <span data-feather="estoque"></span>
              Estoque
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Pessoal
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>-- SUBMENU Produtos</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a <?= $resultadolink = $linkAtual == '/produtosAtivos' || $linkAtual==$prodA.$linkteste ? "class='nav-link active'": "class='nav-link'";?> href="/produtosAtivos">
              <span data-feather="file-text"></span>
              Ativos
            </a>
          </li>
          <li class="nav-item">
            <a <?= $resultadolink = $linkAtual == '/produtosInativos'||$linkAtual==$prodI.$linkteste ? "class='nav-link active'": "class='nav-link'";?> href="/produtosInativos">
              <span data-feather="file-text"></span>
              Inativos
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-bs-toggle="modal" data-bs-target="#novoProduto" type="button">
              <span data-feather="file-text"></span>
              Novo
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-bs-toggle="modal" data-bs-target="#novaClasse" type="button">
              <span data-feather="file-text"></span>
              Classes
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="tab-content" id="nav-tabContent">
        <div <?= $resultadolink = $linkAtual == '/produtosAtivos'|| $linkAtual==$prodA.$linkteste ? "class='tab-pane fade show active'": "class='tab-pane fade show '";?>  id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
          <nav class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"><h1 class="h2">Produtos Ativos</h1> 
          </nav>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Código</th>
                  <th>Descrição</th>
                  <th>Tamanho</th>
                  <th>Acervo min.</th>
                  <th>Acervo max.</th>
                  <th>Classe</th>
                  <th>Id</th>
                  <th>Ação</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach($this->view->produtos as $codProd=>$produto){?>
                  <tr>
                    <td><?=$produto['codProd']?></td>
                    <td><?=$produto['descProd']?></td>
                    <td><?=$produto['tamProd']?></td>
                    <td><?=$produto['estMinProd']?></td>
                    <td><?=$produto['estMaxProd']?></td>
                    <td><?=$produto['classeProd']?></td>
                    <td><?=$produto['idUsuarioFkProd']?></td>
                    <td> 
                      <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#editaProd" data-bs-statusProd="<?=$produto['statusProd']?>" data-bs-codProd="<?=$produto['codProd']?>" data-bs-descProd="<?=$produto['descProd']?>" data-bs-tamProd="<?=$produto['tamProd']?>" data-bs-estMinProd="<?=$produto['estMinProd']?>" data-bs-estMaxProd="<?=$produto['estMaxProd']?>" data-bs-classeProd="<?=$produto['classeProd']?>" data-bs-idUsuarioFkProd="<?=$produto['idUsuarioFkProd']?>"
                        ><small>Editar</small></button>
                        <a href="/deletaProd?delProd=deleta&codProd=<?=$produto['codProd']?>"class="btn btn-danger"><small>Inativar</small></a>
                    </td>
                  </tr> 
                <?php }?>
              </tbody>
            </table>
          </div>
            <nav class="col-md-9 ml-sm-auto col-lg-10 px-md-4" aria-label="Page navigation">
              <ul class="pagination justify-content-end">
                <li class="page-item"><a class="page-link" href="?pagina=1">Primeira</a></li>
                <?php for($i=1;$i<= $this->view->totalPaginas; $i++){ ?>
                <li class="page-item <?=$this->view->paginaAtiva==$i ? 'active':''?>"><a class="page-link " href="?pagina=<?=$i?>"><?=$i?></a></li>
                 <?php }?>
                <li class="page-item"><a class="page-link" href="?pagina=<?=$this->view->totalPaginas?>">Última</a></li>
              </ul>
            </nav>
        </div>
        <div <?= $resultadolink = $linkAtual == '/produtosInativos'|| $linkAtual==$prodI.$linkteste ? "class='tab-pane fade show active'": "class='tab-pane fade show '";?> id="nav-inativos" role="tabpanel" aria-labelledby="nav-inativos-tab">
          <nav class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"><h1 class="h2">Produtos Inativos</h1>
          </nav>
            <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Código</th>
                  <th>Descrição</th>
                  <th>Tamanho</th>
                  <th>Acervo min.</th>
                  <th>Acervo max.</th>
                  <th>Classe</th>
                  <th>Id</th>
                  <th>Ação</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach($this->view->produtosI as $codProd=>$produto){?>
                  <tr>
                    <td><?=$produto['codProd']?></td>
                    <td><?=$produto['descProd']?></td>
                    <td><?=$produto['tamProd']?></td>
                    <td><?=$produto['estMinProd']?></td>
                    <td><?=$produto['estMaxProd']?></td>
                    <td><?=$produto['classeProd']?></td>
                    <td><?=$produto['idUsuarioFkProd']?></td>
                    <td> 
                        <a href="/ativaProd?atiProd=ativa&codProd=<?=$produto['codProd']?>"class="btn btn-warning"><small>Ativar</small></a>
                    </td>
                  </tr> 
                <?php }?>
              </tbody>
            </table>
          </div>
            <nav class="col-md-9 ml-sm-auto col-lg-10 px-md-4" aria-label="Page navigation">
              <ul class="pagination justify-content-end">
                <li class="page-item"><a class="page-link" href="?paginaI=1">Primeira</a></li>
                <?php for($p=1;$p<= $this->view->totalPaginasI; $p++){ ?>
                <li class="page-item <?=$this->view->paginaAtivaI==$p ? 'active':''?>"><a class="page-link " href="?paginaI=<?=$p?>"><?=$p?></a></li>
                 <?php }?>
                <li class="page-item"><a class="page-link" href="?paginaI=<?=$this->view->totalPaginasI?>">Última</a></li>
              </ul>
            </nav>
        </div>
      </div>  
    </main>
<!-- Modal -->
<div class="modal fade" id="novoProduto" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Novo produto</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <form method="POST" action="/postProd">
           <div class="modal-body">
              <div class="mb-3 row">
                <div class="col-9">
                  <input type="text" name="idUsuario" value="<?= $_SESSION['id'];?>" hidden="hidden">
                  <label for="descProd" class="col-form-label">Descrição:</label>
                  <input type="text" class="form-control" id="descProd" name="descProd"  placeholder="Descrição">
                </div>
                <div class="col-3">
                  <label for="tamProd" class="col-form-label">Tamanho:</label>
                  <input type="text" class="form-control" id="tamProd" name="tamProd"  placeholder="Tamanho">
                </div>
              </div>
              <div class="mb-3 row">
                <div class="col-4">
                  <label for="estMinProd" class="col-form-label">Acervo min.</label>
                  <input type="number" class="form-control" id="estMinProd" name="estMinProd" min="1" placeholder="Estoque Min.">
                </div>
                <div class="col-4">
                  <label for="estMaxProd" class="col-form-label">Acervo max.</label>
                  <input type="number" class="form-control" id="estMaxProd" name="estMaxProd" min="1" placeholder="Estoque Máx.">
                </div>
                <div class="col-4">
                  <label for="classeProd" class="col-form-label">Classe:</label>
                  <select class="form-select" aria-label="Default select example" name="classeProd" id="classeProd">
                    <option selected>Selecione...</option>
                    <option value="Alimenticio">Alimentício</option>
                    <option value="Vestuario">Vestuário</option>
                  </select>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close">Cancelar</button>
              <button type="reset" class="btn btn-warning">Limpar</button>
              <button type="submit" class="btn btn-success">Salvar</button>
            </div>
          </form>
      </div>
      
    </div>
  </div>
   <div class="modal fade" id="editaProd" tabindex="-1" aria-labelledby="editaProdLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="editaProdLabel"></h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form method="POST" action="/editProd">
            <div class="modal-body">
              <div class="mb-3 row">
                <div class="col-9">
                  <input type="text" name="codProd" id="codProd"hidden="">
                  <input type="text" name="idUsuario" value="<?= $_SESSION['id'];?>" hidden="hidden">
                  <label for="descProd" class="col-form-label">Descrição:</label>
                  <input type="text" class="form-control" id="descProd" name="descProd"  placeholder="Descrição">
                </div>
                <div class="col-3">
                  <label for="tamProd" class="col-form-label">Tamanho:</label>
                  <input type="text" class="form-control" id="tamProd" name="tamProd" placeholder="Tamanho">
                </div>
              </div>
              <div class="mb-3 row">
                 <div class="col-4">
                  <label for="statusProd" class="col-form-label">Status</label>
                  <input type="text" readonly="readonly" class="form-control" id="statusProd" name="statusProd" placeholder="Status">
                </div>
                <div class="col-4">
                  <label for="estMinProd" class="col-form-label">Acervo min.</label>
                  <input type="number" class="form-control" id="estMinProd" name="estMinProd" min="1" placeholder="Estoque Min.">
                </div>
                <div class="col-4">
                  <label for="estMaxProd" class="col-form-label">Acervo max.</label>
                  <input type="number" class="form-control" id="estMaxProd" name="estMaxProd" min="1" placeholder="Estoque Máx.">
                </div>
              </div>
              <div class="mb-3 row">
                <div class="col-6">
                  <label for="classeProd" class="col-form-label">Classe:</label>
                  <select class="form-select" aria-label="Default select example" name="classeProd" id="classeProd">
                    <option value="Alimenticio">Alimentício</option>
                    <option value="Vestuario">Vestuário</option>
                  </select>
                </div>
                
                  <input type="text" class="form-control" id="classeProd"   placeholder="Classe" readonly="readonly" hidden="">
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close">Cancelar</button>
              <button type="submit" class="btn btn-success">Salvar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="modal fade" id="novaClasse" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="novaClasseLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="novaClasseLabel">Nova classe</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <form method="POST" action="/salvarClasse">
           <div class="modal-body">
              <div class="mb-3 row">
                <div class="col-12">
                  <input type="text" name="idUsuario" value="<?= $_SESSION['id'];?>" hidden="hidden">
                  <label for="classeBase" class="col-form-label">Classe base:</label>
                  <input type="text" class="form-control" id="classeBase" name="classeBase"  placeholder="Ex: Alimenticio, Vestuario ">
                </div>
              </div>
              <div class="mb-3 row">
                <div class="col-12">
                  <label for="classeDivisao" class="col-form-label">Divisão de classe</label>
                  <input type="text" class="form-control" id="classeDivisao" name="classeDivisao"  placeholder="Ex: Perecivel, não Perecivel, Camisa, Cueca">
                </div>
              </div>
                <h6 class="h6 pt-3 pb-2 mb-3 border-bottom">Classes e divisões atuais</h6>
                <div class="mb-3 row">
                  <div class="col-6">
                    <label for="classeProd" class="col-form-label">Classe:</label>
                     <select class="form-select" aria-label="Default select" name="classeProdBase">
            <option selected>Clique para visualizar</option> 
            <?php foreach($this->view->classeProdTotal as $classe=>$classeProdTotal){?>
            <option value="<?=$classeProdTotal['codClasseProd']?>"><?=$classeProdTotal['codClasseProd']?> - <?=$classeProdTotal['classeBase']?></option><?php } ?>
            </select>
                  </div>
                  <div class="col-6">
                    <label for="classeProd" class="col-form-label">Divisão:</label>
                    <select class="form-select" aria-label="Default select" name="classeProdBase">
            <option selected>Clique para visualizar</option> 
            <?php foreach($this->view->divisaoProdTotal as $divisao=>$divisaoProdTotal){?>
            <option value="<?=$divisaoProdTotal['codClasseProd']?>"><?=$divisaoProdTotal['codClasseProd']?> - <?=$divisaoProdTotal['classeDivisao']?></option><?php } ?>
            </select>
                  </div>
                </div>
              </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close">Cancelar</button>
              <button type="reset" class="btn btn-warning">Limpar</button>
              <button type="submit" class="btn btn-success">Salvar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

<script type="text/javascript">
  var editaProd = document.getElementById('editaProd')
    editaProd.addEventListener('show.bs.modal', function (event) {

// Button que altera o estado do modal
    var button = event.relatedTarget

// Enviando valores para variável <--
    var getstatusProd = button.getAttribute('data-bs-statusProd')
    var getcodProd = button.getAttribute('data-bs-codProd')
    var getdescProd = button.getAttribute('data-bs-descProd')
    var gettamProd = button.getAttribute('data-bs-tamProd')
    var getestMinProd = button.getAttribute('data-bs-estMinProd')
    var getestMaxProd = button.getAttribute('data-bs-estMaxProd')
    var getclasseProd = button.getAttribute('data-bs-classeProd')
    var getidUsuarioFkProd = button.getAttribute('data-bs-idUsuarioFkProd')

//Recebendo id do input <--
    var modalTitle = editaProd.querySelector('.modal-title')
    var setstatusProd = editaProd.querySelector('#statusProd')
    var setcodProd = editaProd.querySelector('#codProd')
    var setdescProd = editaProd.querySelector('#descProd')
    var settamProd = editaProd.querySelector('#tamProd')
    var setestMinProd = editaProd.querySelector('#estMinProd')
    var setestMaxProd = editaProd.querySelector('#estMaxProd')
    var setclasseProd = editaProd.querySelector('#classeProd')
    var setidUsuarioFkProd = editaProd.querySelector('#idUsuarioFkProd')



//Exibindo valores recebidos nas variáveis no input dentro do modal <--
    modalTitle.textContent = 'Editar produto de código [ ' + getcodProd + ' ]'
    setcodProd.value = getcodProd
    setstatusProd.value = getstatusProd
    setdescProd.value = getdescProd
    settamProd.value = gettamProd
    setestMinProd.value = getestMinProd
    setestMaxProd.value = getestMaxProd
    setclasseProd.value = getclasseProd
    setidUsuarioFkProd.value = getidUsuarioFkProd
  })
</script>