<html>
	<head>
		<meta charset="utf-8" />
		<title>Projeto Genérico</title>
		<link rel="icon" href="/img/logo.png" type="image/png">
		
		<!-- Versão antiga -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
		<link href="/css/dashboard.css" rel="stylesheet">
		
		<!-- Versão nova --> 
		<!--
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">-->
		

		<script src="https://kit.fontawesome.com/460c10e3ad.js" crossorigin="anonymous"></script>

		<!--	<script src="/js/dashboard.js"></script>
		<script src="/docs/4.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
     	Custom styles for this template -->
    	
		<!--<link rel="stylesheet" type="text/css" href="/css/style.css">-->
		<link rel="stylesheet" type="text/css" href="/css/naforcadoodio.css">

        
		<!-- JavaScript Bundle with Popper -->
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

	</head>

	<body>

		<?= $this->content() ?>
	</body>

</html>